= LibTech1

LibTech1 is a free set of core game assets (levels, graphics, sounds, etc.) to
be used with a https://doomwiki.org/wiki/Source_port[Doom source port].
It is a fork of the https://freedoom.github.io/[Freedoom] project.

Check the https://codeberg.org/mc776/LibTech1/src/branch/main/manual/manual.adoc[manual] for specific instructions.

== What “free” means

You know the phrase "Freedom isn't free"? While nobody's expecting
you to pay for LibTech1, the references to "free software" are supposed
to mean the first rather than the second.

You may freely use LibTech1 for any purpose you see fit. You may
redistribute it to anyone without needing to ask for permission,
you may modify it (provided you keep the license intact, see `COPYING.txt`),
and you may study it--for example, to see how an “IWAD” is built.

You may read more about free software at the https://www.gnu.org/[GNU]
and https://www.fsf.org/[Free Software Foundation] websites. One
may question the wisdom of using the master's tools against the house
they built; but still we charge on, in the hopes of beating at least one
sword into however unnatural-looking a ploughshare it takes.

== Contributing to LibTech1

As a personal project LibTech1 is not accepting unsolicited submissions.
Please inquire with the upstream Freedoom community if there may be any
assets that need updating or replacing.

Please do, however, feel free to post an issue about any bugs or glitches - 
typoes, crashes, softlocks, PWADs that don't load, copyright infringements, 
graphical anomalies, ableist rhetoric, broken game balance, etc..


